modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

# 只装在客户端。配方查看器（JEI/EMI）本身就是客户端模组，
# 而配方数据在客户端也是全量的（原版靠它做配方书），所以没必要做成双端模组。
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"
